// Package shellenv reconstructs a failed step's environment and enters its
// container with a proper interactive shell.
//
// Honesty note: this is a best-effort reconstruction — the workflow env chain
// (workflow → job → step) plus the dynamic $GITHUB_ENV / $GITHUB_PATH deltas
// the run produced inside the container. Values containing unevaluated
// ${{ ... }} expressions are exported literally and flagged in the banner.
package shellenv

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"

	"github.com/Socialpranker/actdbg/internal/state"
)

// EnvsFilePath is where act keeps $GITHUB_ENV inside the job container.
const EnvsFilePath = "/var/run/act/workflow/envs.txt"

// PathsFilePath is where act keeps $GITHUB_PATH inside the job container.
const PathsFilePath = "/var/run/act/workflow/paths.txt"

// CollectSecrets merges a secrets file (KEY=VALUE lines, # comments) with
// repeated -s KEY=VALUE flags. Flag values win.
func CollectSecrets(file string, kvs []string) (map[string]string, error) {
	out := map[string]string{}
	if file != "" {
		b, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("secrets file: %w", err)
		}
		for _, line := range strings.Split(string(b), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			k, v, ok := strings.Cut(line, "=")
			if !ok {
				return nil, fmt.Errorf("secrets file: bad line %q (want KEY=VALUE)", line)
			}
			out[strings.TrimSpace(k)] = strings.Trim(v, `"`)
		}
	}
	for _, kv := range kvs {
		k, v, ok := strings.Cut(kv, "=")
		if !ok {
			return nil, fmt.Errorf("-s %q: want KEY=VALUE", kv)
		}
		out[k] = v
	}
	return out, nil
}

// ParseGithubEnvFile parses the $GITHUB_ENV file format:
//
//	KEY=value
//	KEY<<DELIM
//	multi
//	line
//	DELIM
func ParseGithubEnvFile(content string) map[string]string {
	out := map[string]string{}
	lines := strings.Split(content, "\n")
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if strings.TrimSpace(line) == "" {
			continue
		}
		if k, delim, ok := strings.Cut(line, "<<"); ok && !strings.Contains(k, "=") {
			var val []string
			for i++; i < len(lines); i++ {
				if strings.TrimSpace(lines[i]) == strings.TrimSpace(delim) {
					break
				}
				val = append(val, lines[i])
			}
			out[strings.TrimSpace(k)] = strings.Join(val, "\n")
			continue
		}
		if k, v, ok := strings.Cut(line, "="); ok {
			out[strings.TrimSpace(k)] = v
		}
	}
	return out
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// BuildScript renders the env-restore script sourced inside the container.
func BuildScript(st *state.State, dynamicEnv map[string]string, extraPaths []string) string {
	var b strings.Builder
	b.WriteString("# generated by actdbg\n")
	merged := map[string]string{}
	for k, v := range st.Env {
		merged[k] = v
	}
	for k, v := range dynamicEnv { // $GITHUB_ENV deltas win
		merged[k] = v
	}
	keys := make([]string, 0, len(merged))
	unevaluated := 0
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		v := merged[k]
		if strings.Contains(v, "${{") {
			unevaluated++
		}
		fmt.Fprintf(&b, "export %s=%s\n", k, shellQuote(v))
	}
	for _, p := range extraPaths {
		if p = strings.TrimSpace(p); p != "" {
			fmt.Fprintf(&b, "export PATH=%s:\"$PATH\"\n", shellQuote(p))
		}
	}
	// keep $GITHUB_ENV / $GITHUB_PATH working inside the debug shell
	fmt.Fprintf(&b, "export GITHUB_ENV=%s\nexport GITHUB_PATH=%s\n", EnvsFilePath, PathsFilePath)
	note := ""
	if unevaluated > 0 {
		note = fmt.Sprintf(" · %d value(s) contain unevaluated ${{ }} — exported literally", unevaluated)
	}
	fmt.Fprintf(&b, "echo %s\n", shellQuote(fmt.Sprintf(
		"actdbg: shell at failed step %d/%d %q (job %s) · %d env vars reconstructed, %d from $GITHUB_ENV%s",
		st.StepNumber, st.TotalSteps, st.StepName, st.JobID, len(merged), len(dynamicEnv), note)))
	fmt.Fprintf(&b, "echo %s\n", shellQuote("actdbg: best-effort env — see README §honesty. exit to leave."))
	return b.String()
}

func containerCat(container, path string) string {
	out, err := exec.Command("docker", "exec", container, "cat", path).Output()
	if err != nil {
		return ""
	}
	return string(out)
}

// Enter reconstructs the env and replaces stdio with an interactive shell in
// the saved container.
func Enter(st *state.State) error {
	if err := exec.Command("docker", "inspect", st.Container).Run(); err != nil {
		return fmt.Errorf("container %s is gone (docker inspect failed) — re-run 'actdbg run'", st.Container)
	}
	dyn := ParseGithubEnvFile(containerCat(st.Container, EnvsFilePath))
	var paths []string
	if raw := containerCat(st.Container, PathsFilePath); raw != "" {
		paths = strings.Split(strings.TrimSpace(raw), "\n")
	}
	script := BuildScript(st, dyn, paths)

	// place the script inside the container via stdin (no temp files on host)
	put := exec.Command("docker", "exec", "-i", st.Container, "sh", "-c", "cat > /tmp/actdbg-env.sh")
	put.Stdin = strings.NewReader(script)
	if out, err := put.CombinedOutput(); err != nil {
		return fmt.Errorf("placing env script: %v (%s)", err, strings.TrimSpace(string(out)))
	}

	args := []string{"exec", "-it"}
	if st.Workdir != "" {
		args = append(args, "-w", st.Workdir)
	}
	args = append(args, st.Container, "sh", "-c",
		". /tmp/actdbg-env.sh; exec bash 2>/dev/null || exec sh")
	cmd := exec.Command("docker", args...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	return cmd.Run()
}
